#!/usr/bin/env bash

COLLEEN_SRC="$1"

if [ -z "$COLLEEN_SRC" ]; then
	COLLEEN_SRC="Colleen.c"
fi

COLLEEN_EXEC="${COLLEEN_SRC%.*}"
OUT_FILE="tmp_$COLLEEN_EXEC"

if ! gcc -Wall -Wextra -Werror -o "$COLLEEN_EXEC" "$COLLEEN_SRC"; then
	exit 1
fi

./"$COLLEEN_EXEC" > "$OUT_FILE"

if ! diff "$OUT_FILE" "$COLLEEN_SRC" > /dev/null; then
	echo "KO"
else
	echo "OK"
fi
	
